# coding: utf-8

"""
    Notes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.notes_api import NotesApi


class TestNotesApi(unittest.IsolatedAsyncioTestCase):
    """NotesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = NotesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_notes_get(self) -> None:
        """Test case for notes_get

        Получение всех заметок.
        """
        pass

    async def test_notes_head(self) -> None:
        """Test case for notes_head

        Получение всех заметок.
        """
        pass

    async def test_notes_id_delete(self) -> None:
        """Test case for notes_id_delete

        Удаление заметки.
        """
        pass

    async def test_notes_id_get(self) -> None:
        """Test case for notes_id_get

        Получение заметки по id.
        """
        pass

    async def test_notes_id_head(self) -> None:
        """Test case for notes_id_head

        Получение заметки по id.
        """
        pass

    async def test_notes_id_put(self) -> None:
        """Test case for notes_id_put

        Изменение заметки.
        """
        pass

    async def test_notes_post(self) -> None:
        """Test case for notes_post

        Создание новой заметки
        """
        pass


if __name__ == '__main__':
    unittest.main()
