# coding: utf-8

# flake8: noqa
"""
    Notes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.error_message import ErrorMessage
from openapi_client.models.note import Note
from openapi_client.models.note_text import NoteText

